name: Auto pull
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Pull on develop
      uses: appleboy/ssh-action@master
    - name: Delete Existing Files
      run : sudo ssh -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_PEM }}ec2-user@54.200.237.91 'rm -rf /usr/share/httpd/noindex/* && cd /usr/share/httpd/noindex/ && git pull origin master && git status'
     #with:
      #ssh:
        #host: 54.200.237.91
        #username: ec2-user
        #key: ${{ secrets.SERVER_PEM }}
        #timeout: 60s
        #script: | 
        # cd /usr/share/httpd/noindex/
        # rm -rf *
        # git stash
        # git pull origin master
        # git status
